---
title: "income-inequality"
author: "Junhyeok Park"
date: "2022-12-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(usmap)
```


## Import Relevant Datasets
```{r}
# income percentage generated by top 10% per state
top10 = readxl::read_xls("./data-2/income_ineq_top10.xls")
cols = colnames(top10) %>% stringr::str_match("\n(.+)$")
cols = cols[,2]
cols[1] = "percentile"
cols[2] = "year"
colnames(top10) = cols

top10 = top10 %>%
  rename("Georgia" = "Georgia (US)") %>%
  select(-`Washington D.C.`) %>% 
  filter(year >= 2010)

# convert to longer format
top10 = top10[-1] %>%
  pivot_longer(cols = c("Alabama":"Wyoming"), names_to = "state", values_to = "90th_percentile")

# Accessibility to education
clean_college = function(data_path, is_xlsx=F) {
  df = if (is_xlsx) readxl::read_xlsx(data_path, skip = 1, n_max = 63) else readxl::read_xls(data_path, skip = 1, n_max = 63)
  
  df = df %>%
    rename("state"="State or jurisdiction",
           "num_college"="Total") %>%
    extract(col = state, into = c("state", "state1"), "(.*) (\\.+)") %>%
    select(state, num_college) %>% 
    filter(!is.na(state) & state %in% state.name & state != "District of Columbia")
}

# clean each college data and combine them 
college_2010 = clean_college("./data-2/num-college/num-college-10.xls") %>% mutate(year = 2010)
college_2011 = clean_college("./data-2/num-college/num-college-11.xls") %>% mutate(year = 2011)
college_2012 = clean_college("./data-2/num-college/num-college-12.xlsx", is_xlsx=T) %>% mutate(year = 2012)
college_2013 = clean_college("./data-2/num-college/num-college-13.xlsx", is_xlsx=T) %>% mutate(year = 2013)
college_2014 = clean_college("./data-2/num-college/num-college-14.xls") %>% mutate(year = 2014)
college_2015 = clean_college("./data-2/num-college/num-college-15.xls") %>% mutate(year = 2015)
college_2016 = clean_college("./data-2/num-college/num-college-16.xls") %>% mutate(year = 2016)
college_2017 = clean_college("./data-2/num-college/num-college-17.xls") %>% mutate(year = 2017)
college_2018 = clean_college("./data-2/num-college/num-college-18.xls") %>% mutate(year = 2018)

college_df = rbind(college_2010, college_2011, college_2012, college_2013, college_2014,
                   college_2015, college_2016, college_2017, college_2018) 

# Population: age between 17~25
pop = read_csv("./data-2/sc-est2019-agesex-civ.csv")
  
pop_age_17_25 = pop %>%
  .[, 5:ncol(pop)] %>%
  filter(NAME %in% state.name &
           AGE >= 17 & AGE <= 25) %>%
  select(NAME, AGE, POPEST2010_CIV, POPEST2011_CIV, POPEST2012_CIV, POPEST2013_CIV,
         POPEST2014_CIV, POPEST2015_CIV, POPEST2016_CIV, POPEST2017_CIV, POPEST2018_CIV) %>%
  group_by(NAME) %>%
  summarise(pop_2010 = sum(POPEST2010_CIV),
            pop_2011 = sum(POPEST2011_CIV),
            pop_2012 = sum(POPEST2012_CIV),
            pop_2013 = sum(POPEST2013_CIV),
            pop_2014 = sum(POPEST2014_CIV),
            pop_2015 = sum(POPEST2015_CIV),
            pop_2016 = sum(POPEST2016_CIV),
            pop_2017 = sum(POPEST2017_CIV),
            pop_2018 = sum(POPEST2018_CIV)) %>%
  pivot_longer(-NAME, values_to = "pop_est_17_25", names_to = "year") %>%
  extract(col = year, into = c("year1", "year"), "(.*)_(\\d*)") %>%
  select(-year1) %>%
  rename("state"="NAME") %>%
  mutate(year = as.numeric(year))

# join them together
df = top10 %>%
  left_join(college_df, by=c("year", "state")) %>%
  left_join(pop_age_17_25, by=c("year", "state"))

df %>% head(5)
```

## Analysis
```{r}
df %>%
  filter(year == 2010) %>%
  ggplot(aes(x=log(num_college/pop_est_17_25), y=`90th_percentile`)) +
  geom_point() + 
  xlab('Log of Num Colleges per Person Aged 17-25') + 
  ylab('Proportion national income generated by top 10%') +
  ggtitle('2010')

df %>%
  filter(year == 2011) %>%
  ggplot(aes(x=log(num_college/pop_est_17_25), y=`90th_percentile`)) +
  geom_point() + 
  xlab('Log of Num Colleges per Person Aged 17-25') + 
  ylab('Proportion national income generated by top 10%') +
  ggtitle('2011')

df %>%
  filter(year == 2012) %>%
  ggplot(aes(x=log(num_college/pop_est_17_25), y=`90th_percentile`)) +
  geom_point() + 
  xlab('Log of Num Colleges per Person Aged 17-25') + 
  ylab('Proportion national income generated by top 10%') +
  ggtitle('2012')

df %>%
  filter(year == 2013) %>%
  ggplot(aes(x=log(num_college/pop_est_17_25), y=`90th_percentile`)) +
  geom_point() + 
  xlab('Log of Num Colleges per Person Aged 17-25') + 
  ylab('Proportion national income generated by top 10%') +
  ggtitle('2013')

df %>%
  filter(year == 2014) %>%
  ggplot(aes(x=log(num_college/pop_est_17_25), y=`90th_percentile`)) +
  geom_point() + 
  xlab('Log of Num Colleges per Person Aged 17-25') + 
  ylab('Proportion national income generated by top 10%') +
  ggtitle('2014')

df %>%
  filter(year == 2015) %>%
  ggplot(aes(x=log(num_college/pop_est_17_25), y=`90th_percentile`)) +
  geom_point() + 
  xlab('Log of Num Colleges per Person Aged 17-25') + 
  ylab('Proportion national income generated by top 10%') +
  ggtitle('2015')

df %>%
  filter(year == 2016) %>%
  ggplot(aes(x=log(num_college/pop_est_17_25), y=`90th_percentile`)) +
  geom_point() + 
  xlab('Log of Num Colleges per Person Aged 17-25') + 
  ylab('Proportion national income generated by top 10%') +
  ggtitle('2016')

df %>%
  filter(year == 2017) %>%
  ggplot(aes(x=log(num_college/pop_est_17_25), y=`90th_percentile`)) +
  geom_point() + 
  xlab('Log of Num Colleges per Person Aged 17-25') + 
  ylab('Proportion national income generated by top 10%') +
  ggtitle('2017')

df %>%
  filter(year == 2018) %>%
  ggplot(aes(x=log(num_college/pop_est_17_25), y=`90th_percentile`)) +
  geom_point() + 
  xlab('Log of Num Colleges per Person Aged 17-25') + 
  ylab('Proportion national income generated by top 10%') +
  ggtitle('2018')

```

```{r}
df2010 = df %>%
  filter(year == 2010)
lm2010 = lm(df2010$`90th_percentile` ~ log(df2010$`num_college` / df2010$`pop_est_17_25`))
summary(lm2010)

df2011 = df %>%
  filter(year == 2011)
lm2011 = lm(df2011$`90th_percentile` ~ log(df2011$`num_college` / df2011$`pop_est_17_25`))
summary(lm2011)

df2012 = df %>%
  filter(year == 2012 & state != 'Wyoming')  # Remove outlier
lm2012 = lm(df2012$`90th_percentile` ~ log(df2012$`num_college` / df2012$`pop_est_17_25`))
summary(lm2012)

df2013 = df %>%
  filter(year == 2013)
lm2013 = lm(df2013$`90th_percentile` ~ log(df2013$`num_college` / df2013$`pop_est_17_25`))
summary(lm2013)

df2014 = df %>%
  filter(year == 2014)
lm2014 = lm(df2014$`90th_percentile` ~ log(df2014$`num_college` / df2014$`pop_est_17_25`))
summary(lm2014)

df2015 = df %>%
  filter(year == 2015)
lm2015 = lm(df2015$`90th_percentile` ~ log(df2015$`num_college` / df2015$`pop_est_17_25`))
summary(lm2015)

df2016 = df %>%
  filter(year == 2016)
lm2016 = lm(df2016$`90th_percentile` ~ log(df2016$`num_college` / df2016$`pop_est_17_25`))
summary(lm2016)

df2017 = df %>%
  filter(year == 2017)
lm2017 = lm(df2017$`90th_percentile` ~ log(df2017$`num_college` / df2017$`pop_est_17_25`))
summary(lm2017)

df2018 = df %>%
  filter(year == 2018)
lm2018 = lm(df2018$`90th_percentile` ~ log(df2018$`num_college` / df2018$`pop_est_17_25`))
summary(lm2018)
```


## Resources
- [Income Percentage Generated by Top 10% per State](https://wid.world/data/)
- [Number of Degree-granting Postsecondary Institutions  2010-2018](https://nces.ed.gov/programs/digest)
- [Single Year of Age and Sex Population Estimates: April 1, 2010 to July 1, 2019 - CIVILIAN (SC-EST2019-AGESEX-CIV)](https://www.census.gov/data/tables/time-series/demo/popest/2010s-state-detail.html#par_textimage_673542126)

