---
title: "eda2"
author: "Junhyeok Park"
date: "2022-11-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

## Inequality Data per State

```{r}
# read in the data and rename the columns
top1 = readxl::read_xls("./data/WID_Data_17112022-171839.xls")
cols = colnames(top1) %>% stringr::str_match("\n(.+)$")
cols = cols[,2]
cols[1] = "percentile"
cols[2] = "year"
colnames(top1) = cols
top1 = top1 %>%
  rename("Georgia" = "Georgia (US)") %>%
  select(-`Washington D.C.`)

# pivot longer 
top1 = top1[-1] %>% pivot_longer(cols = c("Alabama":"Wyoming"), names_to = "state", values_to = "99th_percentile")
top1 %>% head(10)
```

## Population

```{r}
# import and preprocess population data 
population = readxl::read_xlsx("./data/population_state.xlsx")
population = population[-1,]
states = population$state %>% stringr::str_match("^\\.(.+)")
states = states[,2]
population$state = states

population = population %>% 
  select(state, "2015":"2018") %>% 
  filter(state != "District of Columbia") %>% 
  pivot_longer(-state, names_to = "year", values_to = "population") %>%
  mutate(year = as.numeric(year))

# joining with inequality data
top1_pop = top1 %>% left_join(population, by = c("year" = "year", "state" = "state"))

# population analysis
top1_pop %>% filter(year == 2018) %>%
  ggplot(aes(population, `99th_percentile`)) +
  geom_point()
```

## Factor 1: Number of Universities
```{r}
# Import / Preprocess the data
college = readxl::read_xls("./data/college.xls")
state_names = college$state %>% stringr::str_match("(.*) \\.+")
college$state = state_names[,2]
college = college %>% select("state", contains("total") | contains("Total"))
college %>% head(10)

# Analysis
top1_pop %>%
  left_join(college, by = "state") %>%
  filter(year == 2018) %>%
  mutate(uni_per_capita = Total / population) %>%
  ggplot(aes(x=uni_per_capita, y=`99th_percentile`)) + 
  geom_point()
```

## Factor 2: Secondary School
```{r}
secondary = readxl::read_xlsx("./data/secondary_edu.xlsx")
 
# student-teacher ratio
top1 %>% 
  left_join(secondary, by = "state") %>%
  filter(year == 2018) %>% 
  ggplot(aes(x=`pupil/teacher ratio`, y=`99th_percentile`)) +
  geom_point()

# secondary school per capita
top1_pop %>% 
  filter(year == 2018) %>% 
  left_join(secondary, by = "state") %>%
  ggplot(aes(x=`operational schools`/population, y=`99th_percentile`)) + 
  geom_point()
```

## Factor 3: Literacy Rate
```{r}
# Import / Preprocess the data
literacy = read_csv("./data/literacy_rate.csv") %>% arrange(state)
literacy
```

## Data Sources

-   [Income Inequality per State](https://wid.world/data/)
-   [Higher Education Data Per State](https://nces.ed.gov/programs/digest/d17/tables/dt17_317.20.asp)
-   [Public Elementary and Secondary Education](https://nces.ed.gov/pubs2018/2018052/tables/table_02.asp)
-   [Literacy Rate]()
